### ISSUE TITLE
Render Error 

### ISSUE THREAD

**Issue by VikAsNeHrA1** [VikAsNeHrA1/Order-Management-app#6]
Any idea ??? why this works on my local but not on my render 

![image](https://github.com/VikAsNeHrA1/Order-Management-app/assets/55554154/86f958e2-bff7-4402-9a1d-5d1710826f2a)

**Comment by VikAsNeHrA1** [comment]
My package.json

![image](https://github.com/VikAsNeHrA1/Order-Management-app/assets/55554154/c3d9e805-894d-48e0-be6c-8d0ec495d8e8)

**Comment by barrycumbie** [comment]
compare to mine:

https://github.com/barrycumbie/cuddly-palm-not-tree-papa-solution/blob/e992493a0f87d0af1faa94cae8b1e943ddba241a/package.json#L19C5-L19C5

**Comment by VikAsNeHrA1** [comment]
*Fixed*

I added Environment Variable in Render and specified the node version manually.
